// VS-01 WP01 — server port of the EXISTING Prototype trade rules.
//
// Source of each rule (must stay in step; tests/unit/rules_parity.test.mjs
// checks golden vectors generated by the GDScript originals):
//   godot/scripts/market_rules.gd     dynamic price, buy / buyback spread
//   godot/scripts/market_prices.gd    baseline prices, initial / target stock
//   godot/scripts/goods_catalog.gd    goods and capacity cost
//   godot/scripts/market_recovery.gd  time-based stock recovery
//   godot/scripts/trade_service.gd    allowed order sizes, order checks
//   godot/scripts/wallet.gd           starting money
//   godot/scripts/character_stats.gd  capacity = 10 + STR x 9, default STR 10
// No value here is a new balance decision. All are Prototype TEST VALUES.
//
// JavaScript numbers are exact only up to 2^53 - 1, so every amount the server
// stores or computes is kept a safe integer (the GDScript save already caps
// stock at 2^53 for the same JSON reason).
//
// Nakama's JS runtime loads one script in global scope, so every name here is
// a global and carries the `rules` prefix.

const RULES_BUY_PERCENT = 105;
const RULES_BUYBACK_PERCENT = 95;
const RULES_MIN_REFERENCE_PRICE = 2;
const RULES_PRICE_SENSITIVITY_PERCENT = 50;
const RULES_DYNAMIC_FLOOR_PERCENT = 50;
const RULES_DYNAMIC_CEILING_PERCENT = 200;
const RULES_RATIO_CAP_BP = 30000;

const RULES_INITIAL_STOCK = 100;
const RULES_TARGET_STOCK = 100;
const RULES_STARTING_MONEY = 10000;
const RULES_MAX_SAFE = 9007199254740991; // Number.MAX_SAFE_INTEGER (ES5 target)
const RULES_ALLOWED_ORDER_QUANTITIES = [1, 10];

const RULES_CAPACITY_BASE = 10;
const RULES_CAPACITY_PER_STRENGTH = 9;
const RULES_DEFAULT_STRENGTH = 10;

const RULES_RECOVERY_STEP_MS = 12000;
const RULES_RECOVERY_STOCK_PER_STEP = 1;
const RULES_RECOVERY_MAX_ELAPSED_MS = 1800000;

const RULES_ACTIVE_CITY_IDS = ["A", "B"];

const RULES_GOODS: { id: string; capacity_cost: number }[] = [
  { id: "test_good_01", capacity_cost: 1 },
  { id: "test_good_02", capacity_cost: 1 },
  { id: "test_good_03", capacity_cost: 2 },
  { id: "test_good_04", capacity_cost: 2 },
  { id: "test_good_05", capacity_cost: 3 },
  { id: "test_good_06", capacity_cost: 4 },
];

const RULES_BASELINE_PRICES: { [city: string]: { [good: string]: number } } = {
  A: { test_good_01: 80, test_good_02: 180, test_good_03: 420, test_good_04: 900, test_good_05: 2100, test_good_06: 3600 },
  B: { test_good_01: 120, test_good_02: 300, test_good_03: 650, test_good_04: 1250, test_good_05: 1700, test_good_06: 4300 },
};

function rulesIsInt(value: any): boolean {
  return typeof value === "number" && isFinite(value) && Math.floor(value) === value
    && value >= -RULES_MAX_SAFE && value <= RULES_MAX_SAFE;
}

function rulesIsPositiveInt(value: any): boolean {
  return rulesIsInt(value) && value > 0;
}

// GDScript integer division (truncates toward zero). (a - a % b) is an exact
// multiple of b, so the division is exact for every safe integer, unlike
// Math.floor(a / b), which can round wrongly near 2^53.
function rulesDiv(a: number, b: number): number {
  return (a - (a % b)) / b;
}

function rulesCityExists(cityId: any): boolean {
  return typeof cityId === "string" && RULES_ACTIVE_CITY_IDS.indexOf(cityId) >= 0;
}

function rulesCapacityCost(goodId: any): number {
  if (typeof goodId !== "string") return 0;
  for (let i = 0; i < RULES_GOODS.length; i++) {
    if (RULES_GOODS[i].id === goodId) return RULES_GOODS[i].capacity_cost;
  }
  return 0;
}

function rulesGoodIds(): string[] {
  const ids: string[] = [];
  for (let i = 0; i < RULES_GOODS.length; i++) ids.push(RULES_GOODS[i].id);
  return ids;
}

function rulesBaselinePrice(cityId: any, goodId: any): number {
  if (!rulesCityExists(cityId) || rulesCapacityCost(goodId) <= 0) return 0;
  const price = RULES_BASELINE_PRICES[cityId][goodId];
  return rulesIsPositiveInt(price) ? price : 0;
}

function rulesIsAllowedQuantity(quantity: any): boolean {
  return rulesIsInt(quantity) && RULES_ALLOWED_ORDER_QUANTITIES.indexOf(quantity) >= 0;
}

// MarketRules._ratio_bp: floor(stock x 10000 / target) by long division.
function rulesRatioBp(stock: number, target: number): number {
  const whole = rulesDiv(stock, target);
  if (whole >= rulesDiv(RULES_RATIO_CAP_BP, 10000)) return RULES_RATIO_CAP_BP;
  let remainder = stock % target;
  let ratio = whole;
  for (let digit = 0; digit < 4; digit++) {
    remainder *= 10;
    ratio = ratio * 10 + rulesDiv(remainder, target);
    remainder %= target;
  }
  return Math.min(ratio, RULES_RATIO_CAP_BP);
}

// MarketRules._scale_ppm: round_half_up(value x factor / 1_000_000).
function rulesScalePpm(value: number, factorPpm: number): number {
  const millions = rulesDiv(value, 1000000);
  const rest = value % 1000000;
  return millions * factorPpm + rulesDiv(rest * factorPpm + 500000, 1000000);
}

function rulesClampReference(baseline: number, raw: number): number {
  const floorPrice = rulesDiv(baseline * RULES_DYNAMIC_FLOOR_PERCENT + 99, 100);
  const ceilingPrice = rulesDiv(baseline, 100) * RULES_DYNAMIC_CEILING_PERCENT
    + rulesDiv((baseline % 100) * RULES_DYNAMIC_CEILING_PERCENT, 100);
  return Math.max(Math.min(Math.max(raw, floorPrice), ceilingPrice), RULES_MIN_REFERENCE_PRICE);
}

function rulesDynamicReference(baseline: number, stock: number, target: number): number {
  if (baseline < RULES_MIN_REFERENCE_PRICE || stock < 0 || target <= 0) return 0;
  const ratioBp = rulesRatioBp(stock, target);
  const factorPpm = 1000000 + (10000 - ratioBp) * RULES_PRICE_SENSITIVITY_PERCENT;
  const raw = rulesScalePpm(baseline, Math.max(factorPpm, 0));
  return rulesClampReference(baseline, raw);
}

function rulesBuyPrice(reference: number): number {
  if (reference < RULES_MIN_REFERENCE_PRICE) return 0;
  return rulesDiv(reference * RULES_BUY_PERCENT + 99, 100);
}

function rulesBuybackPrice(reference: number): number {
  if (reference < RULES_MIN_REFERENCE_PRICE) return 0;
  return rulesDiv(reference * RULES_BUYBACK_PERCENT, 100);
}

function rulesMaxCapacity(strength: number): number {
  return RULES_CAPACITY_BASE + strength * RULES_CAPACITY_PER_STRENGTH;
}

// MarketRecovery.steps_for
function rulesRecoverySteps(elapsedMs: number): number {
  if (!rulesIsInt(elapsedMs) || elapsedMs <= 0) return 0;
  return rulesDiv(Math.min(elapsedMs, RULES_RECOVERY_MAX_ELAPSED_MS), RULES_RECOVERY_STEP_MS);
}

// MarketState.recover_toward_target for one stock value.
function rulesRecoverStock(stock: number, target: number, amount: number): number {
  if (stock < target) return stock + Math.min(amount, target - stock);
  if (stock > target) return stock - Math.min(amount, stock - target);
  return stock;
}
